export const LOG = {
  ADD: 'ADD_LOG',
  CLEAR: 'CLEAR_LOG',
  DELETE: 'DELETE_LOG',
  UPDATE: 'UPDATE_LOG',
  GET: 'GET_LOGS',
  SEARCH: 'SEARCH_LOGS',
  SET_CURRENT: 'SET_CURRENT_LOG',
  CLEAR_CURRENT: 'CLEAR_CURRENT_LOG',
  ERROR: 'LOG_ERROR',
};
export const TECH = {
  ADD: 'ADD_TECH',
  DELETE: 'DELETE_TECH',
  GET: 'GET_TECHS',
  ERROR: 'TECH_ERROR',
};
export const SET_LOADING = 'SET_LOADING';
